project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!data/prep-data.qmd"
  resources:
    - "img/"
    - "data/"

execute:
  freeze: auto

website:
  title: "DAL"
  favicon: img/favicon.png
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: content.qmd
        text: Course content
      - href: assessments.qmd
        text: Assessment
      - href: data.qmd
        text: Data

format:
  html:
    theme: united
    css: styles.css
    toc: true
    df-print: paged
    number-sections: true

callout-icon: false

